export const stickers = {
    animals: {
        'animal-bee': 'Bee',
        'animal-bird': 'Bird',
        'animal-blowfish': 'Blowfish',
        'animal-bluehwhale': 'Blue Whale',
        'animal-bunny': 'Bunny',
        'animal-camel': 'Camel',
        'animal-cat': 'Cat',
        'animal-cow': 'Cow',
        'animal-crab': 'Crab',
        'animal-centipede': 'Centipede',
        'animal-chicken': 'Chicken',
        'animal-clownfish': 'Clownfish',
        'animal-crocodile': 'Crocodile',
        'animal-dog': 'Dog',
        'animal-dolphin': 'Dolphin',
        'animal-duck': 'Duck',
        'animal-elephant': 'Elephant',
        'animal-fish-1': 'Fish',
        'animal-goat': 'Goat',
        'animal-ladybug': 'Ladybug',
        'animal-monkey': 'Monkey',
        'animal-mouse-2': 'Mouse',
        'animal-octopus': 'Octopus',
        'animal-pig': 'Pig',
        'animal-poodle': 'Poodle',
        'animal-sheep': 'Sheep',
        'animal-snail': 'Snail',
        'animal-snake': 'Snake',
        'animal-shrimp': 'Shrimp',
        'animal-spider': 'Spider',
        'animal-spider-2': 'Spider 2',
        'animal-squirrel': 'Squirrel',
        'animal-tiger': 'Tiger',
        'animal-tortoise': 'Tortoise',
        'animal-unicorn': 'Unicorn',
        'animal-whale': 'Whale'
    },
    holidays: {
        'holidays-candle': 'Candle',
        'holidays-gift': 'Gift',
        'holidays-gingerbread': 'Gingerbread',
        'holidays-hat': 'Hat',
        'holidays-tree': 'Tree'
    },
    kano: {
        'arrow': 'Arrow',
        'judoka-face': 'Judoka',
        'planet': 'Planet',
        'judoka-record': 'Record',
        'robotnik': 'Robot',
        'star': 'Star'
    },
    masks: {
        'mask-smile': 'Smile',
        'mask-cool': 'Cool',
        'mask-grin': 'Grinning',
        'mask-laughcry': 'Laughing Crying',
        'mask-meh': 'Meh',
        'mask-rolleyes': 'Rolling Eyes',
        'mask-sleep': 'Sleepy',
        'mask-alien': 'Alien',
        'mask-bear': 'Bear',
        'mask-blank': 'Blank',
        'mask-boar': 'Boar',
        'mask-cat': 'Cat',
        'mask-chicken': 'Chicken',
        'mask-cow': 'Cow',
        'mask-deer': 'Deer',
        'mask-devil': 'Devil',
        'mask-dog': 'Dog',
        'mask-easter-island': 'Easter Island',
        'mask-fox': 'Fox',
        'mask-frog': 'Frog',
        'mask-gorilla': 'Gorilla',
        'mask-horse': 'Horse',
        'mask-koala': 'Koala',
        'mask-lion': 'Lion',
        'mask-mokey': 'Monkey',
        'mask-mouse': 'Mouse',
        'mask-panda': 'Panda',
        'mask-pig': 'Pig',
        'mask-pumpkin': 'Pumpkin',
        'mask-rabbit': 'Rabbit',
        'mask-robot': 'Robot',
        'mask-santa': 'Santa',
        'mask-skull': 'Skull',
        'mask-small-mouse': 'Small Mouse',
        'mask-tiger': 'Tiger',
        'mask-traditional': 'Traditional'
    },
    'food': {
        'food-burger': 'Burger',
        'food-burrito': 'Burrito',
        'food-candy': 'Candy',
        'food-cheese': 'Cheese',
        'food-cherry': 'Cherry',
        'food-chicken': 'Chicken',
        'food-donut': 'Donut',
        'food-eggplant': 'Eggplant',
        'food-icecream': 'Ice Cream',
        'food-melon': 'Melon',
        'food-noodles': 'Noodles',
        'food-peach': 'Peach',
        'food-pineapple': 'Pineapple',
        'food-pizza': 'Pizza',
        'food-shrimp': 'Shrimp',
        'food-sushi': 'Sushi',
        'food-taco': 'Taco',
        'food-tomato': 'Tomato',
        'food-watermelon': 'Watermelon'
    },
    'music': {
        'music-bell': 'Bell',
        'music-drum': 'Drum',
        'music-guitar': 'Guitar',
        'music-musical-note': 'Note',
        'music-musical-notes': 'Notes',
        'music-sax': 'Sax',
        'music-pick': 'Guitar Pick',
        'music-trumpet': 'Trumpet'
    },
    'street art': {
        'bolt': 'Bolt',
        'markers': 'Markers',
        'doubting-donut': 'Doubting Donut',
        'krink-marker': 'Krink Marker',
        'creeper': 'Creeper',
        'mouse': 'Mouse',
        'mrsprinkles': 'Mr. Sprinkles',
        'old-schooler': 'Old Schooler',
        'peace': 'Peace',
        'pixel-spraycan': 'Pixel Spraycan',
        'point': 'Point',
        'rainbow-roller': 'Rainbow Roller',
        'soydog': 'Soydog',
        'spraycan': 'Spraycan',
        'spraying': 'Spraying',
        'star': 'Star',
        'supreme-code': 'Supreme Code'
    },
    'other': {
        'other-avocado': 'Avocado',
        'other-ball': 'Ball',
        'other-ball-baseball': 'Baseball ball',
        'other-ball-basketball': 'Basketball ball',
        'other-cactus': 'Cactus',
        'other-cake': 'Cake',
        'other-clap': 'Clap',
        'other-controller': 'Controller',
        'other-face': 'Face',
        'other-ball-football': 'Football ball',
        'other-ghost': 'Ghost',
        'other-hotdog': 'Hotdog',
        'other-keyboard': 'Keyboard',
        'other-keytar': 'Keytar',
        'other-lightning-bolt': 'Lightning bolt',
        'other-map': 'Map',
        'other-medal': 'Medal',
        'other-medal-2': 'Medal 2',
        'other-microphone': 'Microphone',
        'other-micropscope': 'Microscope',
        'other-minecraft-block': 'Minecraft block',
        'other-palm-tree': 'Palm tree',
        'other-piano-keyboard': 'Piano keyboard',
        'other-popcorn': 'Popcorn',
        'other-pen': 'Pen',
        'other-paintbrush': 'Paintbrush',
        'other-space-invader': 'Space invader',
        'other-ball-tennis': 'Tennis ball',
        'other-thermometer': 'Thermometer',
        'other-toadstool': 'Toadstool',
        'other-trophy': 'Trophy',
        'other-waffles': 'Waffles',
        'other-sprout': 'Sprout',
        'other-palmtree': 'Palmtree',
        'other-clubs': 'Clubs',
        'other-spades': 'Spades',
        'other-hearts': 'Hearts',
        'other-diamonds': 'Diamonds',
        'other-dice': 'Dice',
        'other-eightball': 'Eightball',
        'other-poop': 'Poop'
    },
    'photo-play': {
        'photo-animal-nose': 'Animal nose',
        'photo-boom': 'Boom',
        'photo-crown': 'Crown',
        'photo-ears': 'Ears',
        'photo-eye': 'Eye',
        'photo-eyes': 'Eyes',
        'photo-hearts': 'Hearts',
        'photo-lightbulb': 'Lightbulb',
        'photo-lips': 'Lips',
        'photo-mouth': 'Mouth',
        'photo-nose': 'Nose',
        'photo-bubble-see-speech': 'Speech',
        'photo-bubble-speech-left': 'Speech left',
        'photo-bubble-speech-right': 'Speech right',
        'photo-bubble-speech-urgent': 'Speech urgent',
        'photo-sunglasses': 'Sunglasses',
        'photo-bubble-thought': 'Thought',
        'photo-tongue': 'Tongue',
        'photo-zzz': 'ZZZ'
    },
    'space': {
        'earth-asia': 'Asia',
        'earth-america': 'America',
        'earth-europe': 'Europe',
        'meteor': 'Meteor',
        'moon-1': 'Moon 1',
        'moon-2': 'Moon 2',
        'moon-3': 'Moon 3',
        'moon-4': 'Moon 4',
        'moon-5': 'Moon 5',
        'moon-6': 'Moon 6',
        'moon-7': 'Moon 7',
        'moon-8': 'Moon 8',
        'moon-smiling': 'Moon (smiling)',
        'night-sky': 'Night sky',
        'satellite': 'Satellite',
        'space-rocket': 'Space rocket',
        'star': 'Star',
        'sun-smiling': 'Sun (smiling)',
        'telescope': 'Telescope'
    },
    'vehicles': {
        'ambulance' : 'Ambulance',
        'fire-engine' : 'Fire engine',
        'police-car' : 'Police car',
        'red-car' : 'Red car',
        'taxi' : 'Taxi'
    },
    'obelisk': {
        'obelisk-01': 'Rotor',
        'obelisk-02': 'Anemone',
        'obelisk-03': 'Pulsar',
        'obelisk-04': 'Longboy',
        'obelisk-05': 'Chrysalis',
        'obelisk-06': 'Fidgey',
        'obelisk-07': 'Tendrils',
        'obelisk-08': 'Muscles'
    }
};
