rpi/bin/* /usr/bin
rpi/make_apps /usr/lib/python2.7/dist-packages
www/* /usr/share/make-apps

rpi/icons/MakeApps.lnk usr/share/kano-desktop/kdesk/kdesktop/
rpi/icons/make-apps.app usr/share/applications
rpi/icons/locale/es_AR/*.app /usr/share/applications/locale/es_AR/
rpi/icons/make-apps.png usr/share/icons/Kano/88x88/apps
rpi/icons/kano-code-kdesk-hover.png usr/share/icons/Kano/88x88/apps
rpi/media /usr/share/make-apps/
