export const defaultStamp = 'crocodile';

export const stamps : { id: string, label : string, stickers : { [K : string] : string } }[] = [{
    label: 'Animals',
    id: 'animals',
    stickers: {
        bee: 'animals/animal-bee.svg',
        bird: 'animals/animal-bird.svg',
        blowfish: 'animals/animal-blowfish.svg',
        bluehwhale: 'animals/animal-bluehwhale.svg',
        bunny: 'animals/animal-bunny.svg',
        camel: 'animals/animal-camel.svg',
        cat: 'animals/animal-cat.svg',
        centipede: 'animals/animal-centipede.svg',
        chicken: 'animals/animal-chicken.svg',
        clownfish: 'animals/animal-clownfish.svg',
        cow: 'animals/animal-cow.svg',
        crab: 'animals/animal-crab.svg',
        crocodile: 'animals/animal-crocodile.svg',
        dog: 'animals/animal-dog.svg',
        dolphin: 'animals/animal-dolphin.svg',
        duck: 'animals/animal-duck.svg',
        elephant: 'animals/animal-elephant.svg',
        fish: 'animals/animal-fish-1.svg',
        goat: 'animals/animal-goat.svg',
        ladybug: 'animals/animal-ladybug.svg',
        monkey: 'animals/animal-monkey.svg',
        mouse: 'animals/animal-mouse-2.svg',
        octopus: 'animals/animal-octopus.svg',
        pig: 'animals/animal-pig.svg',
        poodle: 'animals/animal-poodle.svg',
        sheep: 'animals/animal-sheep.svg',
        shrimp: 'animals/animal-shrimp.svg',
        snail: 'animals/animal-snail.svg',
        snake: 'animals/animal-snake.svg',
        spider: 'animals/animal-spider.svg',
        squirrel: 'animals/animal-squirrel.svg',
        tiger: 'animals/animal-tiger.svg',
        tortoise: 'animals/animal-tortoise.svg',
        unicorn: 'animals/animal-unicorn.svg',
        whale: 'animals/animal-whale.svg',
    },
}, {
    label: 'Holidays',
    id: 'holidays',
    stickers: {
        candle: 'holidays/holidays-candle.svg',
        gift: 'holidays/holidays-gift.svg',
        gingerbread: 'holidays/holidays-gingerbread.svg',
        hat: 'holidays/holidays-hat.svg',
        tree: 'holidays/holidays-tree.svg',
    },
}, {
    label: 'Kano',
    id: 'kano',
    stickers: {
        arrow: 'kano/arrow.svg',
        face: 'kano/judoka-face.svg',
        record: 'kano/judoka-record.svg',
        planet: 'kano/planet.svg',
        robotnik: 'kano/robotnik.svg',
        star: 'kano/star.svg',
    },
}, {
    label: 'Masks',
    id: 'masks',
    stickers: {
        alien: 'masks/mask-alien.svg',
        bear: 'masks/mask-bear.svg',
        blank: 'masks/mask-blank.svg',
        boar: 'masks/mask-boar.svg',
        'cat face': 'masks/mask-cat.svg',
        'chicken face': 'masks/mask-chicken.svg',
        cool: 'masks/mask-cool.svg',
        'cow face': 'masks/mask-cow.svg',
        deer: 'masks/mask-deer.svg',
        devil: 'masks/mask-devil.svg',
        'dog face': 'masks/mask-dog.svg',
        'easter island': 'masks/mask-easter-island.svg',
        fox: 'masks/mask-fox.svg',
        frog: 'masks/mask-frog.svg',
        gorilla: 'masks/mask-gorilla.svg',
        grin: 'masks/mask-grin.svg',
        horse: 'masks/mask-horse.svg',
        koala: 'masks/mask-koala.svg',
        laughcry: 'masks/mask-laughcry.svg',
        lion: 'masks/mask-lion.svg',
        meh: 'masks/mask-meh.svg',
        mokey: 'masks/mask-mokey.svg',
        'mouse face': 'masks/mask-mouse.svg',
        panda: 'masks/mask-panda.svg',
        'pig face': 'masks/mask-pig.svg',
        pumpkin: 'masks/mask-pumpkin.svg',
        rabbit: 'masks/mask-rabbit.svg',
        robot: 'masks/mask-robot.svg',
        rolleyes: 'masks/mask-rolleyes.svg',
        santa: 'masks/mask-santa.svg',
        skull: 'masks/mask-skull.svg',
        sleep: 'masks/mask-sleep.svg',
        'small mouse': 'masks/mask-small-mouse.svg',
        smile: 'masks/mask-smile.svg',
        'tiger face': 'masks/mask-tiger.svg',
        traditional: 'masks/mask-traditional.svg',
    },
}, {
    label: 'Food',
    id: 'food',
    stickers: {
        burger: 'food/food-burger.svg',
        burrito: 'food/food-burrito.svg',
        candy: 'food/food-candy.svg',
        cheese: 'food/food-cheese.svg',
        cherry: 'food/food-cherry.svg',
        'chicken leg': 'food/food-chicken.svg',
        donut: 'food/food-donut.svg',
        eggplant: 'food/food-eggplant.svg',
        icecream: 'food/food-icecream.svg',
        melon: 'food/food-melon.svg',
        noodles: 'food/food-noodles.svg',
        peach: 'food/food-peach.svg',
        pineapple: 'food/food-pineapple.svg',
        pizza: 'food/food-pizza.svg',
        tempura: 'food/food-shrimp.svg',
        sushi: 'food/food-sushi.svg',
        taco: 'food/food-taco.svg',
        tomato: 'food/food-tomato.svg',
        watermelon: 'food/food-watermelon.svg',
    },
}, {
    label: 'Music',
    id: 'music',
    stickers: {
        bell: 'music/music-bell.svg',
        drum: 'music/music-drum.svg',
        guitar: 'music/music-guitar.svg',
        note: 'music/music-musical-note.svg',
        notes: 'music/music-musical-notes.svg',
        pick: 'music/music-pick.svg',
        sax: 'music/music-sax.svg',
        trumpet: 'music/music-trumpet.svg',
    },
}, {
    label: 'Street Art',
    id: 'street-art',
    stickers: {
        bolt: 'street art/bolt.svg',
        creeper: 'street art/creeper.svg',
        'doubting donut': 'street art/doubting-donut.svg',
        'krink marker': 'street art/krink-marker.svg',
        markers: 'street art/markers.svg',
        'mouse art': 'street art/mouse.svg',
        mrsprinkles: 'street art/mrsprinkles.svg',
        'old schooler': 'street art/old-schooler.svg',
        peace: 'street art/peace.svg',
        'pixel spraycan': 'street art/pixel-spraycan.svg',
        point: 'street art/point.svg',
        'rainbow roller': 'street art/rainbow-roller.svg',
        soydog: 'street art/soydog.svg',
        spraycan: 'street art/spraycan.svg',
        spraying: 'street art/spraying.svg',
        'graffiti star': 'street art/star.svg',
        supreme: 'street art/supreme-code.svg',
    },
}, {
    label: 'Other',
    id: 'other',
    stickers: {
        avocado: 'other/other-avocado.svg',
        baseball: 'other/other-ball-baseball.svg',
        basketball: 'other/other-ball-basketball.svg',
        football: 'other/other-ball-football.svg',
        tennisball: 'other/other-ball-tennis.svg',
        ball: 'other/other-ball.svg',
        cactus: 'other/other-cactus.svg',
        cake: 'other/other-cake.svg',
        clap: 'other/other-clap.svg',
        controller: 'other/other-controller.svg',
        clubs: 'other/other-clubs.svg',
        diamonds: 'other/other-diamonds.svg',
        hearts: 'other/other-hearts.svg',
        spades: 'other/other-spades.svg',
        dice: 'other/other-dice.svg',
        eightball: 'other/other-eightball.svg',
        'other face': 'other/other-face.svg',
        ghost: 'other/other-ghost.svg',
        hotdog: 'other/other-hotdog.svg',
        keyboard: 'other/other-keyboard.svg',
        keytar: 'other/other-keytar.svg',
        lightning: 'other/other-lightning-bolt.svg',
        map: 'other/other-map.svg',
        medal: 'other/other-medal.svg',
        medal2: 'other/other-medal-2.svg',
        microphone: 'other/other-microphone.svg',
        micropscope: 'other/other-micropscope.svg',
        minecraft: 'other/other-minecraft-block.svg',
        paintbrush: 'other/other-paintbrush.svg',
        palmtree: 'other/other-palmtree.svg',
        pen: 'other/other-pen.svg',
        piano: 'other/other-piano-keyboard.svg',
        poop: 'other/other-poop.svg',
        popcorn: 'other/other-popcorn.svg',
        'space invader': 'other/other-space-invader.svg',
        spider2: 'animals/animal-spider-2.svg',
        sprout: 'other/other-sprout.svg',
        thermometer: 'other/other-thermometer.svg',
        toadstool: 'other/other-toadstool.svg',
        trophy: 'other/other-trophy.svg',
        waffles: 'other/other-waffles.svg',
    },
}, {
    label: 'Photo',
    id: 'data',
    stickers: {
        animal: 'photo-play/photo-animal-nose.svg',
        boom: 'photo-play/photo-boom.svg',
        see: 'photo-play/photo-bubble-see-speech.svg',
        'speech left': 'photo-play/photo-bubble-speech-left.svg',
        'speech right': 'photo-play/photo-bubble-speech-right.svg',
        'speech urgent': 'photo-play/photo-bubble-speech-urgent.svg',
        'thought': 'photo-play/photo-bubble-thought.svg',
        crown: 'photo-play/photo-crown.svg',
        ears: 'photo-play/photo-ears.svg',
        eye: 'photo-play/photo-eye.svg',
        eyes: 'photo-play/photo-eyes.svg',
        heart: 'photo-play/photo-hearts.svg',
        lightbulb: 'photo-play/photo-lightbulb.svg',
        lips: 'photo-play/photo-lips.svg',
        mouth: 'photo-play/photo-mouth.svg',
        nose: 'photo-play/photo-nose.svg',
        sunglasses: 'photo-play/photo-sunglasses.svg',
        tongue: 'photo-play/photo-tongue.svg',
        zzz: 'photo-play/photo-zzz.svg',
    },
}, {
    label: 'Space',
    id: 'space',
    stickers: {
        america: 'space/earth-america.svg',
        asia: 'space/earth-asia.svg',
        europe: 'space/earth-europe.svg',
        meteor: 'space/meteor.svg',
        moon: 'space/moon-1.svg',
        moon2: 'space/moon-2.svg',
        moon3: 'space/moon-3.svg',
        moon4: 'space/moon-4.svg',
        moon5: 'space/moon-5.svg',
        moon6: 'space/moon-6.svg',
        moon7: 'space/moon-7.svg',
        moon8: 'space/moon-8.svg',
        'moon smiling': 'space/moon-smiling.svg',
        night: 'space/night-sky.svg',
        satellite: 'space/satellite.svg',
        rocket: 'space/space-rocket.svg',
        'shining star': 'space/star.svg',
        'sun smiling': 'space/sun-smiling.svg',
        telescope: 'space/telescope.svg',
    },
}, {
    label: 'Vehicles',
    id: 'vehicles',
    stickers: {
        ambulance: 'vehicles/ambulance.svg',
        'fire engine': 'vehicles/fire-engine.svg',
        police: 'vehicles/police-car.svg',
        'red car': 'vehicles/red-car.svg',
        taxi: 'vehicles/taxi.svg',
    },
}];
